name = "graph_coloring"
version = "0.1.0"
keywords = ["math", "graph theory", "list coloring"]
defaultTargets = ["Monophilic"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "905b95818eb32af7874a58b427f50c1711a5e96c"

[[lean_lib]]
name = "Monophilic"
