import Lake
open Lake DSL

require verso from git "https://github.com/leanprover/verso" @ "v4.33.0"
require graph_coloring from ".."

-- `warningAsError` is the point of this block. Verso's failure path for a backticked name it
-- cannot resolve — inside a rendered `{docstring}`, and inside the book's own prose — is
-- `logWarningAt`, not `throwError` (see `tryElabInlineCodeUsing` in Verso's `Docstring.lean`), so
-- a reference to a declaration that no longer exists otherwise renders happily as plain code and
-- the build stays green. Promoting warnings to errors is what makes a stale reference fail CI.
--
-- The one linter that has to be switched off for that to be usable is `verso.code.warnLineLength`:
-- it is purely typographic (default 60 columns), it fires on the book's own displayed `example`s
-- and on library docstrings, which carry their own line widths, and it has nothing to do with
-- whether a name resolves. `linter.verso.markup.emph` is deliberately left ON — the book's prose
-- is kept clean of it — and is disabled only in `Book/Reference.lean`, where library docstrings
-- written in Markdown (`**bold**`) are rendered verbatim.
package book where
  leanOptions := #[
    ⟨`experimental.module, false⟩, ⟨`autoImplicit, false⟩, ⟨`relaxedAutoImplicit, false⟩,
    ⟨`warningAsError, true⟩,
    ⟨`verso.code.warnLineLength, (0 : Nat)⟩]

-- NOTE: deliberately no `lean_exe`. Linking a native executable that imports Mathlib forces
-- compilation of all of Mathlib to object code (~2700 jobs, several GB). The book is generated by
-- running `Main.lean` through the interpreter instead:
--     lake env lean --run Main.lean
@[default_target]
lean_lib Book where
  roots := #[`Book]
