import Lake
open Lake DSL

require verso from git "https://github.com/leanprover/verso" @ "v4.32.0"
require graph_coloring from ".."

package book where
  leanOptions := #[⟨`experimental.module, false⟩, ⟨`autoImplicit, false⟩, ⟨`relaxedAutoImplicit, false⟩]

-- NOTE: deliberately no `lean_exe`. Linking a native executable that imports Mathlib forces
-- compilation of all of Mathlib to object code (~2700 jobs, several GB). The book is generated by
-- running `Main.lean` through the interpreter instead:
--     lake env lean --run Main.lean
@[default_target]
lean_lib Book where
  roots := #[`Book]
